### ISSUE TITLE
Issue - order products endpoint displaying no data

### ISSUE THREAD

**Issue by sparkweb** [createdotnet/API-Documentation#31]
I'm trying to download order products and I'm getting a "No data found" return.

https://api.create.net/orders/1370274/products
https://api.create.net/orders/946316/products

^ just a couple of examples.

**Comment by sparkweb** [comment]
Is there any other data I can provide over email which would assist in troubleshooting this issue?

**Comment by EdBailey** [comment]
Hi, sorry about the delay replying to this.

I can see that those particular orders are several years old and don't appear to have any products attached to them. This may have been caused by an issue at the time so is probably nothing to worry about.
It's likely that in any case of it returning "No data found" for order products that there are no products associated.

I hope this helps

**Comment by sparkweb** [comment]
Thanks for the reply. I'll ask the customer to place a couple of test orders.
